# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457a9a4fcc808b3aa6dfcd51b93b725db4c5562c1394370b2d12b17798d77aaf5933371788dd0aedaa525f77a04d52bf52253b6c782b04fd9566753f9f1bd737

test:
  secret_key_base: 6b9cdba8470a035b09b3ec7a66160deaa366a32976d7a08648c5602ee8bbb10d670063312ca1b51e829f9bb3d20376e7ff28871c439032055804ba9c9de777f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
